import React,{button, useState} from "react";
import './styles/style.css';

const data = [
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"},
    {"url": "https://unsplash.com/photos/2LowviVHZ-E", "title": "A Sea Turtle's Journey"},
    {"url": "https://unsplash.com/photos/WLxQvbMyfas", "title": "Urban Exploration"},
    {"url": "https://unsplash.com/photos/qyAka7W5uMY", "title": "Winter's Beach"},
    {"url": "https://unsplash.com/photos/lRoX0shwjUQ", "title": "Mountain Solitude"},
    {"url": "https://unsplash.com/photos/EwKXn5CapA4", "title": "Floral Whispers"},
    {"url": "https://unsplash.com/photos/8manzosDSGM", "title": "Abstract Horizons"},
    {"url": "https://unsplash.com/photos/ZRns2R5azu0", "title": "Serene Waters"},
    {"url": "https://unsplash.com/photos/kFCdfLbu6zA", "title": "Vase of Simplicity"},
    {"url": "https://unsplash.com/photos/u3WmDyKGsrY", "title": "Palm Shadows"},
    {"url": "https://unsplash.com/photos/LjqARJaJotc", "title": "Blossom in Focus"},
    {"url": "https://unsplash.com/photos/7Zb7kUyQg1E", "title": "Sunglass Reflections"},
    {"url": "https://unsplash.com/photos/NodtnCsLdTE", "title": "Rocky Contemplation"},
    {"url": "https://unsplash.com/photos/jFCViYFYcus", "title": "Botanical Beauty"},
    {"url": "https://unsplash.com/photos/wR11KBaB86U", "title": "Skyward Blooms"},
    {"url": "https://unsplash.com/photos/b2haCjfk_cM", "title": "Sunset Silhouettes"},
    {"url": "https://www.pexels.com/photo/low-angle-shot-of-man-holding-jacket-1031231/", "title": "Modernist Muse"},
    {"url": "https://www.pexels.com/photo/green-fern-leaf-on-mountains-background-1588270/", "title": "Mountain Fern"},
    {"url": "https://www.pexels.com/photo/woman-surfing-during-daytime-3052861/", "title": "Surf's Up"},
    {"url": "https://www.pexels.com/photo/woman-in-ripped-jeans-standing-3363723/", "title": "Urban Casual"},
    {"url": "https://www.pexels.com/photo/woman-in-pink-suit-walking-3651816/", "title": "Pink on the Pavement"}
]


export default function LoadMoreButton () {
    function addImages() {
        setCurrentCountImages(currCountImages + 10);
    }

    const [currCountImages, setCurrentCountImages] = useState(10);
    const maxCount = 100;

    return (
        <div>
            <div className="wrapper">
                {data.map((row, index) => (
                    <div key={index} className={index >= currCountImages ? `displayNone` : ''}>
                        {
                        index <= currCountImages ?<div className="colContainer">
                                <div className="imageContainer" style={{backgroundImage:`url(${data[index].url})`}}></div> 
                                <div>{row.title}</div>
                        </div>
                        : ''}
                    </div>
                    ))}
            </div>
            {currCountImages >= maxCount 
                ?  
                <div>
                    <button disabled onClick={addImages}>Load more Products</button> 
                    <div>You have Reached 100 Products</div>
                </div> 
                :       
                <button onClick={addImages}>Load more Products</button>
            }
        </div>
        
    )
}